Adjust speed buttons (and other modification refactoring)
conveyal/analysis-ui pull request #1150
Opened 2020-07-20 04:45 UTC by trevorgerhardt

2020-08-31 05:51 UTC, ansoncfit commented on lib/components/modification/adjust-speed.tsx
> +  }
The Add To mode only works if a segment has first been selected using the Select mode. Otherwise, an `Invalid attempt to spread non-iterable instance` error occurs. This behavior is present on dev, not just this branch.

2020-09-07 06:33 UTC, trevorgerhardt commented on lib/components/modification/adjust-speed.tsx
> +  }
This has been fixed

2020-09-07 06:34 UTC, trevorgerhardt commented
This PR is code ready and ready for another review, but integration tests are failing and could use the Cypress changes introduced in #1199 to help pass.

2020-09-13 17:38 UTC, ansoncfit requested changes
Testing this out, the remove-stops updates look good. There's still a bit of confusing behavior/instructions with the adjust-speed modifications.

2020-09-13 17:38 UTC, ansoncfit commented on lib/components/modifications-map/draw-polygon.js
> +          circlemarker: false
👍

2020-09-13 17:38 UTC, ansoncfit commented on lib/components/modification/adjust-speed.tsx
> +      )}
If `hops==null`, the speed factor applies to the entirety of the selected patterns, so the color should be `colors.MODIFIED`.

If `hops!=null` (i.e. only a subset of the patterns have speed adjusted), then there should be a NEUTRAL layer below the MODIFIED layer.

Does this code supersede `lib/components/modifications-map/adjust-speed-layer.js` LL 10-36?

2020-09-13 17:38 UTC, ansoncfit commented on lib/components/modification/adjust-speed.tsx
> +                onClick={() => setAction('remove')}
This action appears to have the opposite effect of what's intended. If a set of hops A-B-C is selected, drawing a polygon to remove subset A-B appears to remove subset B-C.

I'm not sure how commonly this remove-hops feature is used, so maybe we should just eliminate it.

2020-09-13 17:38 UTC, ansoncfit commented on lib/components/modification/adjust-speed.tsx
> +            {message('report.adjustSpeed.selectInstructions')}
This message should be updated, maybe with some conditional logic.

If `hops == null`, 

"Speed adjustment will apply to entire pattern(s). Use button below to limit the adjustment to certain segments."

else

"Speed adjustment will apply only to selected segments."

2020-09-14 02:58 UTC, trevorgerhardt commented on lib/components/modification/adjust-speed.tsx
> +      )}
We had a distinction between the "editing" map components of a modification and non-editing map components. I moved the editing components directly into the individual modification components.

2020-09-14 03:09 UTC, trevorgerhardt commented on lib/components/modification/adjust-speed.tsx
> +                onClick={() => setAction('remove')}
There was a note about the logic there. Corrected it. Works now! This problem exists on production too.

2020-09-14 13:06 UTC, ansoncfit commented on lib/components/modification/adjust-speed.tsx
> +      )}
Just discussed: the code in `lib/components/modifications-map/adjust-speed-layer.js` is not duplicative -- it's separate logic for "view-only" display of the modification.

2020-09-14 13:07 UTC, ansoncfit approved these changes
Thanks for the fixes

2020-09-15 14:14 UTC, merged