Presets (previously known as Bookmarks)
conveyal/analysis-ui pull request #1227
Opened 2020-09-08 12:48 UTC by trevorgerhardt

This PR enables preset management. Deleting, editing names, filtering, and viewing the properties of the presets.

- [ ] Database migration from bookmarks to presets
- [ ] Address #471 (maybe?)

closes #638

2020-09-16 08:59 UTC, abyrd commented
I'm reviewing this but having some trouble interpreting what I'm seeing. Several files are added or changed in `lib/components/modification/`, can you explain briefly how this is connected to saving presets? Also, am I correct in understanding that preset storage is using the new catch-all `/api/db/x` endpoints, and if so can you point out where (in what file) that API call would be made?

2020-09-16 10:59 UTC, trevorgerhardt commented on lib/hooks/use-model.ts
> +export const useAnalysisPreset = createUseModel('analysisPreset')
This needs to be corrected to `usePreset = createUseModel('presets')`

2020-09-16 11:00 UTC, trevorgerhardt commented
> I'm reviewing this but having some trouble interpreting what I'm seeing. Several files are added or changed in `lib/components/modification/`, can you explain briefly how this is connected to saving presets? Also, am I correct in understanding that preset storage is using the new catch-all `/api/db/x` endpoints, and if so can you point out where (in what file) that API call would be made?

Are you accidentally looking at a merge commit? There aren't any files changed under `/lib/components/modification` in this PR specifically.

The preset storage is using the new catch-all api routes. In order to use them, I created helper "hooks" for CRUD actions. See `lib/hooks/use-model` and `lib/hooks/use-collection`. This both have simple factory functions that encapsulate the collection name, so we have a `usePreset(id)` hook created in `use-model` and a `usePresets()` hook created in `use-collection`.

Each additional collection we can just add a line to the `use-model` file and `use-collection` file like:
```tsx
// use-model
export const useProject = createUseModel('projects')

// use-collection
export const useProjects = createUseCollection('projects')
```

2020-09-22 17:17 UTC, ansoncfit requested changes
Great to see these updates and the ability to rename/delete presets. A few cleanup items:

- It appears that creating a preset before the origin marker has been moved (i.e. when it defaults to the center of the region) saves the preset without `fromLat` and `fromLon` values. This means once the marker is moved, loading (and by extension, editing or deleting) the preset is not possible unless the user manually moves the origin back to the initial location exactly.

- Working through this behavior, it occurred to me that we could make the relocation of the origin marker to a preset's saved `fromLat`/`fromLon` optional, either by giving the option to include origin coordinates when saving a preset (and not resetting the origin location for presets saved without origin coordinates), or by adding a move origin to preset location button with the preset options. That's additional functionality, so we could table it.

- Logic for the "Identical request settings" switch in the comparison request should be checked. With the current implementation, if a preset is loaded for the comparison request, it can have different settings than the main analysis but still show up with "identical request settings" true.

2020-09-22 17:17 UTC, ansoncfit commented on migrations/1599703681398-bookmarks-to-presets.js
> +})
Looks like a pretty straightforward migration.

2020-09-22 17:17 UTC, ansoncfit commented on lib/components/analysis/egress-mode-selector.js
> -import {faBicycle, faWalking} from '@fortawesome/free-solid-svg-icons'
With egress mode now handled in the `ModeSelector` component, this is unused 👍

2020-09-22 17:52 UTC, ansoncfit commented on lib/components/presets.tsx
> +    <Modal isOpen={true} onClose={onClose} initialFocusRef={nameInput.ref}>
`closeOnOverlayClick={false}` here and in the other added Modals?

2020-09-23 05:06 UTC, trevorgerhardt commented on lib/auth0.ts
> +// Initialzed auth0s per origin served from this lambda
Updated

2020-09-23 05:15 UTC, trevorgerhardt commented on lib/components/presets.tsx
> +        })
Yea, another pull request addressed an issue with the confirm dialog that changed this functionality.

2020-09-23 05:16 UTC, trevorgerhardt commented on lib/components/presets.tsx
> +    <Modal isOpen={true} onClose={onClose} initialFocusRef={nameInput.ref}>
Added 👍

2020-09-23 05:36 UTC, trevorgerhardt commented
> * It appears that creating a preset before the origin marker has been moved (i.e. when it defaults to the center of the region) saves the preset without `fromLat` and `fromLon` values. This means once the marker is moved, loading (and by extension, editing or deleting) the preset is not possible unless the user manually moves the origin back to the initial location exactly.

> * Working through this behavior, it occurred to me that we could make the relocation of the origin marker to a preset's saved `fromLat`/`fromLon` optional, either by giving the option to include origin coordinates when saving a preset (and not resetting the origin location for presets saved without origin coordinates), or by adding a move origin to preset location button with the preset options. That's additional functionality, so we could table it.

Hmm...ok, this is definitely a problem. I am more inclined to go with one default than add additional options. I think it would be clearer to always save the origin and always load the preset to the origin. If a user wants to delete/edit a preset they can always reselect it which would move it back to the correct origin.

> * Logic for the "Identical request settings" switch in the comparison request should be checked. With the current implementation, if a preset is loaded for the comparison request, it can have different settings than the main analysis but still show up with "identical request settings" true.

Fixed 👍

2020-09-23 05:46 UTC, trevorgerhardt commented
With the full separation we could even add an additional origin marker for the comparison.

2020-09-24 02:17 UTC, ansoncfit approved these changes
Thanks for the additional changes.

2020-09-24 02:29 UTC, merged