Move CSS into individual components
conveyal/analysis-ui pull request #1512
Opened 2021-03-16 01:04 UTC by trevorgerhardt

This should make the initial page load faster.

2021-03-16 21:22 UTC, ansoncfit requested changes
With fontawesome gone, `className='fa-spin'` should be updated in a couple places.

2021-03-16 21:47 UTC, trevorgerhardt commented
> With fontawesome gone, `className='fa-spin'` should be updated in a couple places.

Ah yes, forgot we were still using that.

Btw, we're still using FontAwesome icons, but now importing each icon directly as SVG through `react-icons`.

2021-03-16 21:47 UTC, trevorgerhardt commented
> With fontawesome gone, `className='fa-spin'` should be updated in a couple places.

Fixed 👍

2021-03-17 01:24 UTC, ansoncfit approved these changes

2021-03-17 01:24 UTC, merged