Display GTFS errors
conveyal/analysis-ui pull request #1526
Opened 2021-04-22 01:07 UTC by trevorgerhardt

Display stored errors generated while processing GTFS feeds.

Additionally, adds an experimental `Combobox` component that could eventually replace the `Select` component. It's not currently used in the application, but there's a test page added that uses it.

Also, fixes #1011 

## How to test

1. Create a bundle with a GTFS feed that will contain errors.
2. View the errors after the bundle creation is complete.

2021-04-22 01:13 UTC, trevorgerhardt commented
#### 📝Changed routes:


| [**/debug/select**](https://analysis-esjgrvb4b-conveyal.vercel.app/debug/select) | [**…Id\]/bundles/\[bundleId\]**](https://analysis-esjgrvb4b-conveyal.vercel.app/regions/[regionId]/bundles/[bundleId]) |
|:-:|:-:|
|<a href="https://analysis-esjgrvb4b-conveyal.vercel.app/debug/select"><img src="https://images.weserv.nl?url=https://s.microlink.io/jRy0oh-rL1lNS6WyFs1W_gOCNeDguBuAIXLCWOW34uk9z0oCi7QRCv9rOlo4Q7P-fP5bK0PH96qd-Nzcvt4C2w.png&w=600" alt="Screenshot of /debug/select" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Yx5OHBAyx1QBx3NIMX8L49VIz6yK2331ALf6td6S6fQ60kO1HJ8RcCj8TJiMdm1AyH9h7LRPgIEEq9eUgj__kA.png">(view full size)</a> |<a href="https://analysis-esjgrvb4b-conveyal.vercel.app/regions/[regionId]/bundles/[bundleId]"><img src="https://images.weserv.nl?url=https://s.microlink.io/uuSftZNYsrcNjKJVgW475u1ARWZH7asr9zViIrudOsCgSjvqFg05H3lb-ES_LaLB5-oJXKyu42gOk43R1eLV2w.png&w=600" alt="Screenshot of /regions/[regionId]/bundles/[bundleId]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/D_Kl7dbhxHVbzGgo1TH2kyprgQQTHg-3_sKk9sMpU2cE1gXmmZJaTJUFis66lJopn0LaURsAv7qM5n6PJ0WHVA.png">(view full size)</a> |



| [**…ons/\[regionId\]/bundles**](https://analysis-esjgrvb4b-conveyal.vercel.app/regions/[regionId]/bundles) |
|:-:|
|<a href="https://analysis-esjgrvb4b-conveyal.vercel.app/regions/[regionId]/bundles"><img src="https://images.weserv.nl?url=https://s.microlink.io/P4eCMFkBSIzu6U4ZOZ7XL22sbrvfjAgocsOcn2f9qrt6Ljl-WlK9ojXqwkEwE_oMrKGB8ETayoUgEEFVRkCXPQ.png&w=600" alt="Screenshot of /regions/[regionId]/bundles" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/1H21qHqmYlHhfiF8E3pZlPQzA7dF3O8voa9tXnei5cb0HccXZSXoq-CDZynQFY4tSeotgb6I4NBNRsR-PB0rsw.png">(view full size)</a> |





2 deleted routes:
- **/regions/[regionId]/bundles/[bundleId]**
- **/regions/[regionId]/bundles**

Commit 1bf383966a7adc166d12adb453772fa680f30321 (https://analysis-esjgrvb4b-conveyal.vercel.app).

2021-04-29 19:35 UTC, ansoncfit requested changes
I like the error summary display. I flagged one issue and a few small suggestions below.

2021-04-29 19:35 UTC, ansoncfit commented on lib/components/create-project.tsx
> +      b.feeds.every((f) => f.errors.every((e) => e.priority !== 'HIGH'))
After uploading the feed with invalid references (shared previously), the create project page shows this error: `Cannot read property 'every' of undefined` (https://analysis-git-display-gtfs-errors-conveyal.vercel.app/regions/5a2e9df732b98e221fef89eb/create-project)

2021-04-29 19:35 UTC, ansoncfit commented on lib/components/edit-bundle.tsx
> +          Note: only the first ten errors of each type are saved.
```suggestion
          plus {error.count - 10} more errors of this type.
```

Also suggest moving this into the collapse above -- shouldn't need to be shown when boxes are collapsed.

2021-04-29 19:35 UTC, ansoncfit commented on lib/components/edit-bundle.tsx
> +        <AlertTitle flex='2' fontSize='xl'>
Add `onClick={onToggle}` to the title too, so users don't have to click precisely on the chevron?

2021-04-30 01:18 UTC, trevorgerhardt commented on lib/components/create-project.tsx
> +      b.feeds.every((f) => f.errors.every((e) => e.priority !== 'HIGH'))
Should be fixed 👍

2021-04-30 01:22 UTC, ansoncfit approved these changes
Thanks for incorporating the suggestions.

2021-04-30 01:24 UTC, merged