Regional analyses fetch refactor
conveyal/analysis-ui pull request #1567
Opened 2021-06-02 06:12 UTC by trevorgerhardt

2021-06-11 00:37 UTC, ansoncfit requested changes
Overall regional analysis creation/comparison works on staging -- just a couple styling/padding issues I noticed.

2021-06-11 00:37 UTC, ansoncfit commented on lib/aggregation-area/components/chart.tsx
> +        accessToName={p.accessToName}
Padding:

![image](https://user-images.githubusercontent.com/2173529/121613731-264e4400-ca2b-11eb-85b2-c50aa6c34e76.png)

2021-06-14 05:05 UTC, trevorgerhardt commented on lib/regional/components/active-analysis-page.tsx
> +      />
Removed them while the job is running 👍

2021-06-14 05:11 UTC, trevorgerhardt commented on lib/aggregation-area/components/chart.tsx
> +        accessToName={p.accessToName}
Fixed 👍

2021-06-18 01:18 UTC, ansoncfit approved these changes

2021-06-18 01:18 UTC, merged